# Generated by Django 3.2.3 on 2021-05-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitems_review_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
