# Generated by Django 3.2.3 on 2021-05-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210520_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/default_product.png', null=True, upload_to=''),
        ),
    ]
